// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyiuszotgsjlcmzdauby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5aXVzem90Z3NqbGNtemRhdWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjYxODYsImV4cCI6MjA3MjA0MjE4Nn0.Y5OuIBYZEpZX8OG8O3ZPrWM1Lt-oJTuLQfFdNuEL25M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});